
# Schema for the configuration files of the Persistent Identifiers Field Module module.
persistent_fields.settings:
  type: config_object
  label: 'Persistent Identifiers Field Module settings'
  mapping:
    example:
      type: string
      label: 'Example'
